
services:
  savvi_verify:
    build:
      context: .
      dockerfile: dockerfile.dev
    env_file:
      - .env.prod
      - .env.dev # second because it overrides the first
    ports:
      - "${AUTH_PORT}:8080"
    volumes:
      - .:/app
    depends_on:
      - db
